[[redirects]]
  from = "https://test2.map.avoin.org/_next/*"
  to = "https://test.map.avoin.org/_next/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://test2.map.avoin.org"
  to = "https://test.map.avoin.org/hiilikartta"
  status = 200
  force = true


[[redirects]]
  from = "https://test2.map.avoin.org/*"
  to = "https://test.map.avoin.org/hiilikartta/:splat"
  status = 200
  force = true
